import { ethers } from "hardhat";

async function main() {
  console.log("🚀 Starting local SecretVoteGovernance deployment...\n");

  // Get deployer account
  const [deployer] = await ethers.getSigners();
  console.log("📝 Deploying contracts with account:", deployer.address);
  console.log("💰 Account balance:", ethers.formatEther(await ethers.provider.getBalance(deployer.address)), "ETH\n");

  // For local testing, use deployer as both gateway and admin
  const gatewayAddress = deployer.address; // Mock gateway
  const adminAddress = deployer.address;

  console.log("👤 Admin address:", adminAddress);
  console.log("🔐 Gateway address (mock):", gatewayAddress, "\n");

  // Deploy contract
  console.log("📦 Deploying SecretVoteGovernance contract...");
  const SecretVoteGovernance = await ethers.getContractFactory("SecretVoteGovernance");
  const secretVote = await SecretVoteGovernance.deploy(gatewayAddress, adminAddress);

  await secretVote.waitForDeployment();
  const contractAddress = await secretVote.getAddress();

  console.log("✅ SecretVoteGovernance deployed to:", contractAddress);
  console.log("");

  // Verify deployment
  console.log("🔍 Verifying deployment...");
  const proposalCount = await secretVote.getProposalCount();
  console.log("   Initial proposal count:", proposalCount.toString());

  // Check admin role
  const ADMIN_ROLE = await secretVote.ADMIN_ROLE();
  const hasAdminRole = await secretVote.hasRole(ADMIN_ROLE, adminAddress);
  console.log("   Admin has ADMIN_ROLE:", hasAdminRole);

  console.log("\n✨ Deployment completed successfully!\n");

  // Print deployment summary
  console.log("📋 Deployment Summary:");
  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
  console.log("Contract Address:", contractAddress);
  console.log("Gateway Address:", gatewayAddress);
  console.log("Admin Address:", adminAddress);
  console.log("Network:", (await ethers.provider.getNetwork()).name);
  console.log("Chain ID:", (await ethers.provider.getNetwork()).chainId);
  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n");

  // Grant roles for testing
  console.log("🔑 Granting roles for local testing...");
  const VOTER_ROLE = await secretVote.VOTER_ROLE();
  const PROPOSER_ROLE = await secretVote.PROPOSER_ROLE();

  // Grant roles to first 3 accounts
  const signers = await ethers.getSigners();
  for (let i = 0; i < Math.min(3, signers.length); i++) {
    await secretVote.grantRole(VOTER_ROLE, signers[i].address);
    await secretVote.grantRole(PROPOSER_ROLE, signers[i].address);
    console.log(`   ✓ Granted roles to account ${i}: ${signers[i].address}`);
  }

  // Save deployment info to file
  const fs = require('fs');
  const deploymentInfo = {
    address: contractAddress,
    network: "localhost",
    chainId: Number((await ethers.provider.getNetwork()).chainId),
    gatewayAddress,
    adminAddress,
    deployedAt: new Date().toISOString(),
    accounts: signers.slice(0, 3).map((s, i) => ({
      index: i,
      address: s.address,
      roles: ["VOTER", "PROPOSER", i === 0 ? "ADMIN" : null].filter(Boolean)
    }))
  };

  fs.writeFileSync(
    './deployment-local.json',
    JSON.stringify(deploymentInfo, null, 2)
  );
  console.log("\n💾 Deployment info saved to deployment-local.json");

  // Save frontend config
  const frontendConfig = `// Auto-generated by deploy-local.ts
export const CONTRACT_ADDRESS = "${contractAddress}";
export const CONTRACT_CHAIN_ID = ${deploymentInfo.chainId};
export const GATEWAY_ADDRESS = "${gatewayAddress}";

export const TEST_ACCOUNTS = ${JSON.stringify(deploymentInfo.accounts, null, 2)};
`;

  fs.writeFileSync(
    './src/config/contract.ts',
    frontendConfig
  );
  console.log("💾 Frontend config saved to src/config/contract.ts\n");

  console.log("\n📚 Next steps:");
  console.log("1. Start the frontend: npm run dev");
  console.log("2. Connect MetaMask to localhost:8545");
  console.log("3. Import test account private key:");
  console.log(`   ${deployer.address}`);
  console.log("\n✅ Ready to test! The contract is deployed and configured.");

  return contractAddress;
}

main()
  .then((address) => {
    console.log("\n✅ Deployment script completed successfully");
    process.exit(0);
  })
  .catch((error) => {
    console.error("\n❌ Deployment failed:");
    console.error(error);
    process.exit(1);
  });
